### PR TITLE
Add GT version checks to avoid crash with GT6

### PR DESCRIPTION
**Pull request by kappa-maintainer**
I don't want to use the origin Magic Bees...

### CODE REVIEW

**Comment by Dream-Master** [comment]
@kappa-maintainer the dev branch is a test branch. If you make a pr please make it to master branch.

**Comment by kappa-maintainer** [comment]
But this problem doesn't exist in master branch? Where should I get a copy of build from master

**Comment by Dream-Master** [comment]
Dev branch contains only open prs for testing

**Comment by chochem** [comment]
if the problem exists in dev branch but not in master, then you should check which open PR is the problem and comment there or PR to it.

**Comment by Dream-Master** [comment]
<https://github.com/GTNewHorizons/MagicBees/pull/34/files#diff-979543754a4682a6e959dab88d4d190f1e989be954fddb3e24e402e35e37b594R167>

**Pull request merged**
